name: deltachat-desktop
base: core22
version: 1.40.3
summary: Delta Chat is a messaging app that works over e-mail
description: |
    Delta Chat is a new chat app that sends messages via e-mails, encrypted if possible, with Autocrypt.
    You do not have to sign up anywhere, just use your existing e-mail account with Delta Chat.

    Source: https://download.delta.chat/desktop/
    Snap-Source: https://github.com/nbuechner/deltachat-snap

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    build-for: amd64

apps:
  deltachat-desktop:
    command: ./deltachat-desktop --no-sandbox --dev-mode --log-to-console
    plugs: [home, x11, desktop, removable-media, network, audio-record, audio-playback, shared-memory ]
    extensions: [ gnome ]
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

plugs:
  shared-memory:
    private: true

parts:
  main:
    source: https://github.com/deltachat/deltachat-desktop/archive/refs/tags/v$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: npm
    npm-include-node: true
    npm-node-version: 18.17.1
    override-build: |
        cp src/main/tray.ts src/main/tray.ts.bak
        cp src/renderer/components/dialogs/Settings-Advanced.tsx src/renderer/components/dialogs/Settings-Advanced.tsx.bak
        npm install electron-builder
        npm install electron@latest
        patch -p1 < /root/project/snap/local/patches/tray-patch.diff
        npm run build
        npm run pack:linux:dir
        mv src/main/tray.ts.bak src/main/tray.ts
        mv src/renderer/components/dialogs/Settings-Advanced.tsx.bak src/renderer/components/dialogs/Settings-Advanced.tsx
        cp -rv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/
    build-environment:
      - npm_config_unsafe_perm: 'true'
      - SUDO_UID: '0'
      - SUDO_GID: '0'
      - SUDO_USER: 'root'
      - VERSION_INFO_GIT_REF: ${SNAPCRAFT_PROJECT_VERSION}
    stage-packages:
       - libgtk-3-0
       - libnotify4
       - libnss3
       - libxss1
       - libxtst6
       - xdg-utils
       - libatspi2.0-0
       - libuuid1
       - libsecret-1-0
lint:
  ignore:
    - library

