name: deltachat-desktop
base: core22
version: 1.40.1
summary: Delta Chat is a messaging app that works over e-mail
description: |
    Delta Chat is a new chat app that sends messages via e-mails, encrypted if possible, with Autocrypt.
    You do not have to sign up anywhere, just use your existing e-mail account with Delta Chat.

    Source: https://download.delta.chat/desktop/
    Snap-Source: https://github.com/nbuechner/deltachat-snap

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    build-for: amd64

apps:
  deltachat-desktop:
    command: opt/DeltaChat/deltachat-desktop --no-sandbox
    plugs: [home, x11, desktop, removable-media, network, audio-record, audio-playback, shared-memory ]
    extensions: [ gnome ]

plugs:
  shared-memory:
    private: true

parts:
  main:
    source: https://download.delta.chat/desktop/v${SNAPCRAFT_PROJECT_VERSION}/deltachat-desktop_${SNAPCRAFT_PROJECT_VERSION}_amd64.deb
    plugin: dump
    source-type: deb
    override-build: |
      craftctl default
    stage-packages:
       - libappindicator3-1
       - libgtk-3-0
       - libnotify4
       - libnss3
       - libxss1
       - libxtst6
       - xdg-utils
       - libatspi2.0-0
       - libuuid1
       - libsecret-1-0
lint:
  ignore:
    - library

