name: Build and publish snap to stable channel
on: workflow_dispatch
permissions:
  contents: write
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - arm64
        - amd64
    steps:
      - name: Get latest release and store artifact
        id: get_release
        run: |
          # Store the newly fetched release version in a file
          RELEASE_TAG=$(curl -s https://api.github.com/repos/deltachat/deltachat-desktop/releases/latest | jq -r '.tag_name')
          echo "${RELEASE_TAG}" > deltachat-release-info
          echo "Saved ${RELEASE_TAG} to deltachat-release-info"
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Upload new artifact
        id: upload_artifact
        uses: actions/upload-artifact@v3
        with:
          name: deltachat-release-info
          path: deltachat-release-info
      - uses: docker/setup-qemu-action@v3
      - name: Snapcraft build
        id: snapcraft_build
        uses: diddlesnaps/snapcraft-multiarch-action@v1
        with:
           architecture: ${{ matrix.platform }}
      - name: Snapcraft publish
        id: snapcraft_publish
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.snapcraft_build.outputs.snap }}
          release: stable
