name: Push commit on version update
on: workflow_dispatch
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Commit version update
      - uses: actions/checkout@v4
        run: |
          RELEASE_TAG=$(curl -s https://api.github.com/repos/deltachat/deltachat-desktop/releases/latest | jq -r '.tag_name' | cut -c2-)
          sed -i "/^\([[:space:]]*version: \).*/s//\1$RELEASE_TAG/" snapcraft.yaml
          git config --global user.name 'Nils Büchner'
          git config --global user.email 'nils@buechner.me'
          git commit -am "Automated version update to $RELEASE_TAG"
          git push
      - name: Upload new artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deltachat-release-info
          path: deltachat-release-info
